### ISSUE TITLE
account being accessed does not support http

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck-plugins/rundeck-azure-plugin#11]
Rundeck 3.1

**bug**

When "Secure Transfer Required" is enabled in the azure server, we are getting this error:

```at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
at java.lang.Thread.run(Thread.java:748)

[2019-09-13 04:18:03.710] ERROR LogFileStorageService --- [tp1804109458-80] Failed to initialize LogFileStoragePlugin 'azure-storage': com.microsoft.azure.storage.StorageException: The account being accessed does not support http.

com.microsoft.azure.storage.StorageException: The account being accessed does not support http.
at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175)
at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94)
at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:769)
at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:379)
at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:326)
at com.microsoft.azure.storage.blob.CloudBlobContainer$createIfNotExists.call(Unknown Source)
at com.rundeck.plugins.azure.plugin.AzureFileStoragePlugin.initialize(AzureFileStoragePlugin.groovy:115)
```

**Comment by kulmam92** [comment]
@ltamaster 
I'm still having this issue even though I'm using azure-plugin-1.0.5.jar

`ERROR LogFileStorageService --- [eduler_Worker-1] Failed to initialize LogFileStoragePlugin 'azure-storage': com.microsoft.azure.storage.StorageException: The account being accessed does not support http.`

Would you doublecheck if the fix is working?

**Comment by gbnord** [comment]
@kulmam92 
Try to add: 
framework.plugin.ExecutionFileStorage.azure-storage.defaultEndpointProtocol=https
in framework.properties. 
It worked for me.
