### ISSUE TITLE
Test result failed when running /gradlew build

### ISSUE THREAD

**Issue by Ein-nor** [rundeck-plugins/rundeck-azure-plugin#21]
Hello,

I am not a developer, but I need a small change in this plugin (as described here: [https://github.com/rundeck-plugins/rundeck-azure-plugin/issues/7](https://github.com/rundeck-plugins/rundeck-azure-plugin/issues/7)).

When running "./gradlew build" on my Mac, I get the following message:
`java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
	at groovy.json.internal.FastStringUtils$StringImplementation$1.toCharArray(FastStringUtils.java:88)
	at groovy.json.internal.FastStringUtils.toCharArray(FastStringUtils.java:175)
	at groovy.json.internal.CharBuf.addJsonFieldName(CharBuf.java:543)
	at groovy.json.JsonOutput.writeMap(JsonOutput.java:424)
	at groovy.json.JsonOutput.writeObject(JsonOutput.java:270)
	at groovy.json.JsonOutput.writeIterator(JsonOutput.java:442)
	at groovy.json.JsonOutput.writeObject(JsonOutput.java:272)
	at groovy.json.JsonOutput.toJson(JsonOutput.java:190)
	at com.rundeck.plugins.azure.plugin.AzureVmListPlugin.executeStep(AzureVmListPlugin.groovy:134)
	at com.rundeck.plugins.azure.plugin.AzureVmListPluginSpec.retrieve resource success(AzureVmListPluginSpec.groovy:55)`

I'm using Java 11:
`❯ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)`

How can I fix this problem?

**Comment by Ein-nor** [comment]
Problem solved, I've swichted to AdoptOpenJDK8.
