### ISSUE TITLE
Cannot invoke method name() on null object - Nullpointer Exception

### ISSUE THREAD

**Issue by dkingkumar** [rundeck-plugins/rundeck-azure-plugin#8]
Virtual Machine: /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/TSL-ZE2-C-RPM-RG/providers/Microsoft.Compute/virtualMachines/ze2crundeck01
Name: ze2crundeck01
Resource group: TSL-ZE2-C-RPM-RG
Region: eastus2
Tags: {environment=shared, project=rundeck, team=rpm, Rundeck-Tags=shared,rundeck,rpm}
HardwareProfile:
Size: standard_d4s_v3
StorageProfile:
ID:/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/TSL-ZE2-C-RPM-RG/providers/Microsoft.Compute/virtualMachines/ze2crundeck01
VM-ID:a123456-d375-4c9f-a9a1-ae9qytw18557
ImageReference:
Publisher: center-for-internet-security-inc
Offer: cis-centos-7-v2-1-1-l1
SKU: cis-centos7-l1
Version: 3.0.1
OSDisk:
OSType: Linux
Name: ze2crundeck01-os
Caching: ReadWrite
CreateOption: fromImage
DiskSizeGB: 200
OSProfile:
ComputerName:ze2crundeck01
LinuxConfiguration:
DisablePasswordAuthentication: true
NetworkProfile:
Id:/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/TSL-ZE2-C-RPM-RG/providers/Microsoft.Network/networkInterfaces/ze2crundeck01-ni
Extensions:
Extension: /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/TSL-ZE2-C-RPM-RG/providers/Microsoft.Compute/virtualMachines/ze2crundeck01/extensions/enablevmaccess
Name: enablevmaccess
Tags: {}
ProvisioningState: Failed
Auto upgrade minor version enabled: false
Publisher: Microsoft.OSTCExtensions
Type: VMAccessForLinux
Version: 1.4
Public Settings: null
MSI:
MSI enabled:false
MSI Active Directory Service Principal Id:null
MSI Active Directory Tenant Id:null
Zones: []

ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.source (azure-resource-model), project: TestCloudProject] java.lang.NullPointerException: Cannot invoke method name() on null object at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91) at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at com.microsoft.azure.management.resources.fluentcore.arm.models.HasName$name.call(Unknown Source) at com.rundeck.plugins.azure.azure.AzureNode.<init>(AzureNode.groovy:87) at sun.reflect.GeneratedConstructorAccessor390.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83) at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59) at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:110) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258) at com.rundeck.plugins.azure.azure.AzureManager$_listVms_closure3.doCall(AzureManager.groovy:105) at sun.reflect.GeneratedMethodAccessor928.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at groovy.lang.Closure.call(Closure.java:418) at groovy.lang.Closure.call(Closure.java:434) at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125) at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110) at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151) at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source) at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) at com.rundeck.plugins.azure.azure.AzureManager.listVms(AzureManager.groovy:95) at com.rundeck.plugins.azure.azure.AzureManager$listVms$17.call(Unknown Source) at com.rundeck.plugins.azure.plugin.AzureResourceModelSource.getNodes(AzureResourceModelSource.groovy:65) at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57) at com.dtolabs.rundeck.core.common.ProjectNodeSupport$LoadedSource.getNodes(ProjectNodeSupport.java:456) at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:138) at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:365) at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes$0.call(Unknown Source) at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44) at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source) at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:290) at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy) at sun.reflect.GeneratedMethodAccessor1385.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at groovy.lang.Closure.call(Closure.java:418) at groovy.lang.Closure.call(Closure.java:412) at com.codahale.metrics.Timer.time(Timer.java:99) at com.codahale.metrics.Timer$time$0.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at com.codahale.metrics.Timer$time$0.call(Unknown Source) at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:57) at sun.reflect.GeneratedMethodAccessor1384.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190) at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:104) at rundeck.services.NodeService.loadNodes(NodeService.groovy:302) at sun.reflect.GeneratedMethodAccessor1378.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225) at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:95) at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy) at rundeck.services.NodeService$3.methodMissing(NodeService.groovy) at sun.reflect.GeneratedMethodAccessor1308.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:951) at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1279) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1227) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822) at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177) at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:138) at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at groovy.lang.Closure.call(Closure.java:418) at groovy.lang.Closure.call(Closure.java:412) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:271) at java.lang.Thread.run(Thread.java:748)

Getting same error with Rundeck Version - 3.0.13, 3.0.12, 3.0.8

**Comment by fdevans** [comment]
Sorry we missed this.  If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
